export const SLUGS = {
  archaeology: 'archaeology',
  art: 'folk-applied-art',
  contacts: 'contacts',
  exhibit: 'exhibit',
  exhibitions: 'exhibitions',
  exposition: 'exposition',
  friends: 'friends',
  gallery: 'gallery',
  history: 'history',
  library: 'library',
  museum: 'museum',
  projects: 'projects',
  restoration: 'restoration-section',
  shop: 'book-shop',
  visits: 'visits',
};
