query GetPage($slug: String!) {
  pageCollection(limit: 1, where: { slug: $slug }) {
    items {
      sys {
        id
      }
      nameEn
      nameRu
      nameUz
      nameKa
      descriptionEn {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          },
          assets {
            block {
              sys {
                id
              }
              url
              title
              width
              height
            }
          }
        }
      }
      descriptionRu {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          },
          assets {
            block {
              sys {
                id
              }
              url
              title
              width
              height
            }
          }
        }
      }
      descriptionUz {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          },
          assets {
            block {
              sys {
                id
              }
              url
              title
              width
              height
            }
          }
        }
      }
      descriptionKa {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          },
          assets {
            block {
              sys {
                id
              }
              url
              title
              width
              height
            }
          }
        }
      }
    }
  }
}
