query GetExhibit($slug: String!) {
  exhibitCollection(limit: 1, where: { slug: $slug }) {
    items {
      nameEn
      authorEn
      yearOfCreation
      descriptionEn {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          }
        }
      }
      imagesCollection(limit: 5) {
        items {
          url
          sys {
            id
          }
        }
      }
    }
  }
}
