name: Deploy to Firebase Hosting on release
'on':
  release:
    types: [released]
env:
  VITE_CONTENTFUL_SPACE_ID: ${{secrets.VITE_CONTENTFUL_SPACE_ID}}
  VITE_CONTENTFUL_CONTENT_DELIVERY_ACCESS_TOKEN: ${{secrets.VITE_CONTENTFUL_CONTENT_DELIVERY_ACCESS_TOKEN}}
  VITE_CONTENTFUL_CONTENT_PREVIEW_ACCESS_TOKEN: ${{secrets.VITE_CONTENTFUL_CONTENT_PREVIEW_ACCESS_TOKEN}}
  VITE_CONTENTFUL_ENVIRONMENT: ${{secrets.VITE_CONTENTFUL_ENVIRONMENT}}
  VITE_CONTENTFUL_GTAG_ID: ${{secrets.VITE_CONTENTFUL_GTAG_ID}}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAVITSKY_MUSEUM }}'
          channelId: live
          projectId: savitsky-museum
          target: savitsky-museum