name: Continuous Deployment to Netlify

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [released]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test
      - name: Deploy Preview to Netlify
        if: github.event_name == 'pull_request'
        run: |
          npx netlify deploy \
            --build \
            --site ${{ secrets.NETLIFY_STAGING_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
      - name: Deploy Staging to Netlify
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npx netlify deploy \
            --build \
            --prod \
            --site ${{ secrets.NETLIFY_STAGING_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
      - name: Deploy Production to Netlify
        if: github.event_name == 'release' && github.event.action == 'released'
        run: |
          npx netlify deploy \
            --build \
            --prod \
            --site ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
